module.exports = {
  JOIN_APP: 'JOIN_APP',
  LEAVE_APP: 'LEAVE_APP',
  CLIENT_SEND_NEW_MESSAGE: 'CLIENT_SEND_NEW_MESSAGE',
  SERVER_SEND_NEW_MESSAGE: 'SERVER_SEND_NEW_MESSAGE',
  CLIENT_SEND_MESSAGE_ERROR: 'CLIENT_SEND_MESSAGE_ERROR',
}
